### ISSUE TITLE
rssgenerator.rb - throws error on build.

### ISSUE THREAD

**Issue by scottbaron** [agelber/jekyll-rss#15]
☺ jekyll serve --watch --drafts --baseurl"" ruby-2.2.1
Configuration file: /Users/scottbaron/www/superblog/_config.yml
Source: /Users/scottbaron/www/superblog
Destination: /Users/scottbaron/www/superblog/_site
Incremental build: disabled. Enable with --incremental
Generating...
Deprecation: Collection#map should be called on the #docs array
directly.
Called by
/Users/scottbaron/www/superblog/_plugins/rssgenerator.rb:45:in `block in
generate'.
Deprecation: Collection#count should be called on the #docs
array directly.
Called by
/Users/scottbaron/www/superblog/_plugins/rssgenerator.rb:48:in `block in
generate'.
Deprecation: Collection#reverse should be called on the #docs
array directly.
Called by
/Users/scottbaron/www/superblog/_plugins/rssgenerator.rb:50:in `block in
generate'.
jekyll 3.0.1 | Error: undefined method `render' for
#<Jekyll::Document:0x007f84b31aa718>
git_prompt:1: command not found: current_branch

**Comment by agelber** [comment]
Thanks! Will get around to fixing this.

**Comment by agelber** [comment]
By the way, I see that in the new versions Jekyll, you get a `feed.xml` in the default site template. Is there any reason you prefer to use this?

**Comment by agelber** [comment]
So anyway, this is resolved now.
Thanks for your help! :beers:

**Comment by scottbaron** [comment]
Thank you. Please permit me another question. As an oleh, my english 
speaking friends are very limited. I current don't have an adviser to 
consult with and have a question or
2 regarding JS and JQ, I won't ask you to be my tutor but I would love 
to speak with you, if you have the time.  PLease consider this I can be 
reached at 054-937-1844.  Essentially,
I get JQ, but every programmer seems to use different patters. I get the 
idea of scope, anyway could we please talk. Thank you and shavuah tove.

**Comment by scottbaron** [comment]
I did see that, but the course I was using pointed to your code. That is 
when I decided to give you the heads up. Thank you.

**Comment by agelber** [comment]
I will gladly help you out, but I prefer to do it over chat, Google Hangouts possibly or something similar.
You have my email address, so let's schedule something.

(And you may want to delete the comment with your phone number)

**Comment by scottbaron** [comment]
we can do it over skype if that works for you. my name on skype is scott 
baron if you send me an invite i will respond asap
thank you very much.
